### ISSUE TITLE
Atomics/memory fences

### ISSUE THREAD

**Issue by maciejkula** [Netflix/vectorflow#22]
Out of curiosity: do you use any atomic instructions/emit memory fences when performing Hogwild! parameter updates?

**Comment by rostyboost** [comment]
No, because of the added runtime cost. I'm fairly confident that for some models and datasets there's a sparsity pattern regime where it would make sense though: when race conditions happen more frequently (thus hurting convergence more - on somewhat dense features with a lot of cores at work for example) but not too frequently (in which case HogWild! will fail altogether).

**Comment by maciejkula** [comment]
Cool, that was my intuition as well.
